import { Institution } from "@/types";

export const MOCK_INSTITUTIONS: Institution[] = [
  {
    id: "disdukcapil",
    name: "Dinas Kependudukan dan Pencatatan Sipil",
    description: "Pelayanan administrasi kependudukan: KTP, KK, Akta Kelahiran, dan dokumen sipil lainnya.",
    category: "Administrasi",
    address: "Jl. Pahlawan No. 1, Kota Surabaya",
    rating: 4.2,
    totalResponses: 1823,
    satisfactionRate: 87,
  },
  {
    id: "puskesmas-center",
    name: "Puskesmas Pusat Kota",
    description: "Pelayanan kesehatan dasar, pemeriksaan umum, vaksinasi, dan layanan ibu & anak.",
    category: "Kesehatan",
    address: "Jl. Diponegoro No. 45, Kota Surabaya",
    rating: 4.5,
    totalResponses: 2341,
    satisfactionRate: 92,
  },
  {
    id: "bppt",
    name: "Badan Pelayanan Perizinan Terpadu",
    description: "Pengurusan izin usaha, IMB, SIUP, TDP, dan berbagai perizinan lainnya dalam satu atap.",
    category: "Perizinan",
    address: "Jl. Ahmad Yani No. 100, Kota Surabaya",
    rating: 3.8,
    totalResponses: 987,
    satisfactionRate: 74,
  },
  {
    id: "samsat",
    name: "Samsat — Pelayanan Pajak Kendaraan",
    description: "Pembayaran pajak kendaraan bermotor, BPKB, STNK, dan mutasi kendaraan.",
    category: "Perpajakan",
    address: "Jl. Raya Darmo No. 22, Kota Surabaya",
    rating: 4.0,
    totalResponses: 3102,
    satisfactionRate: 81,
  },
  {
    id: "dinsos",
    name: "Dinas Sosial",
    description: "Pelayanan sosial, bantuan masyarakat, verifikasi PKH, dan layanan penyandang disabilitas.",
    category: "Sosial",
    address: "Jl. Embong Malang No. 8, Kota Surabaya",
    rating: 4.3,
    totalResponses: 756,
    satisfactionRate: 89,
  },
  {
    id: "disnaker",
    name: "Dinas Ketenagakerjaan",
    description: "Layanan bursa kerja, penempatan tenaga kerja, pelatihan, dan mediasi hubungan industrial.",
    category: "Ketenagakerjaan",
    address: "Jl. Gubernur Suryo No. 13, Kota Surabaya",
    rating: 3.9,
    totalResponses: 542,
    satisfactionRate: 78,
  },
  {
    id: "dishub",
    name: "Dinas Perhubungan",
    description: "Pelayanan uji kir kendaraan, izin trayek, parkir resmi, dan manajemen lalu lintas.",
    category: "Perhubungan",
    address: "Jl. Ksatrian No. 9, Kota Surabaya",
    rating: 3.7,
    totalResponses: 413,
    satisfactionRate: 72,
  },
  {
    id: "dinas-pendidikan",
    name: "Dinas Pendidikan",
    description: "Layanan PPDB, mutasi siswa, beasiswa, akreditasi sekolah, dan administrasi pendidikan.",
    category: "Pendidikan",
    address: "Jl. Jagir Wonokromo No. 354, Kota Surabaya",
    rating: 4.1,
    totalResponses: 1205,
    satisfactionRate: 83,
  },
  {
    id: "bpbd",
    name: "Badan Penanggulangan Bencana Daerah",
    description: "Layanan tanggap darurat bencana, evakuasi, logistik kebencanaan, dan mitigasi risiko.",
    category: "Kebencanaan",
    address: "Jl. Arif Rahman Hakim No. 5, Kota Surabaya",
    rating: 4.6,
    totalResponses: 298,
    satisfactionRate: 94,
  },
  {
    id: "disperdagin",
    name: "Dinas Perdagangan",
    description: "Layanan metrologi, pengawasan barang beredar, izin pasar, dan perlindungan konsumen.",
    category: "Perdagangan",
    address: "Jl. Tunjungan No. 50, Kota Surabaya",
    rating: 3.6,
    totalResponses: 367,
    satisfactionRate: 69,
  },
  {
    id: "bkpsdm",
    name: "Badan Kepegawaian Daerah",
    description: "Pelayanan administrasi ASN: kenaikan pangkat, mutasi pegawai, pensiun, dan penilaian kinerja.",
    category: "Kepegawaian",
    address: "Jl. Jimerto No. 25, Kota Surabaya",
    rating: 4.0,
    totalResponses: 634,
    satisfactionRate: 80,
  },
  {
    id: "rsud",
    name: "RSUD Dr. Soetomo",
    description: "Pelayanan rawat inap, rawat jalan, UGD, spesialis, dan rujukan tingkat lanjut.",
    category: "Kesehatan",
    address: "Jl. Mayjen Prof. Dr. Moestopo No. 6, Kota Surabaya",
    rating: 4.4,
    totalResponses: 4521,
    satisfactionRate: 90,
  },
];

export const MOCK_STATS = {
  totalResponses: 17_000,
  totalInstitutions: 48,
  averageSatisfaction: 4.2,
};

export const MOCK_RESULT = {
  disdukcapil: {
    institutionId: "disdukcapil",
    institutionName: "Dinas Kependudukan dan Pencatatan Sipil",
    averageRating: 4.2,
    satisfactionRate: 87,
    totalResponses: 1823,
    distribution: [
      { score: 1, count: 28 },
      { score: 2, count: 54 },
      { score: 3, count: 185 },
      { score: 4, count: 732 },
      { score: 5, count: 824 },
    ],
    positiveCount: 1556,
    negativeCount: 267,
  },
};
